spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: c:///upload
  config:
    activate:
      on-profile: local
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:///C:/upload/

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  datasource:
    url: jdbc:postgresql://localhost:5432/newbalance
    username: postgres
    password: apfhd1
#    driver-class-name: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/webapp

  board:
    paging:
      size: 10

server:
  url: http://localhost:8080